default:

  path_raw_pbp:
    default: 'data-raw/pbp_with_lineup.csv'
    help: 'Path format of raw play-by-play data file to clean.'
    
    
  path_game_final_scores_error:
    default: 'data/01-clean/dump/error/game_final_scores_error.csv'
    help: ''
  path_pbp_error:
    default: 'data/01-clean/dump/error/pbp_error.csv'
    help: 'Path format of '
  path_pbp:
    default: 'data/01-clean/pbp.csv'
    help: 'Path format of cleaned play-by-play data file.'

    
  path_lineup_summary_calc:
    default: 'data/02-munge/dump/calc/lineup_summary_calc.csv'
    help: 'Path format of '
  path_players_game_logs_compare:
    default: 'data/02-munge/dump/compare/players_game_logs_compare.csv'
    help: ''
  path_players_summary_compare:
    default: 'data/02-munge/dump/compare/players_summary_compare.csv'
    help: ''
  path_teams_summary_compare:
    default: 'data/02-munge/dump/compare/teams_summary_compare.csv'
    help: ''
  path_players_summary_calc:
    default: 'data/02-munge/dump/calc/players_summary_calc.csv'
    help: 'Path format of summarized cleaned player data.
     Relevant in the same cases as `path_poss_o`.
     Used to add names and other player-relevant information to final output.'
  path_teams_summary_calc:
    default: 'data/02-munge/dump/calc/teams_summary_calc.csv'
    help: 'Analogous to `path_players_summary_calc` for team data.'
  path_poss_long_error_side:
    default: 'data/02-munge/dump/debug/poss_long_error.csv'
    help: 'Path format of '
  path_poss_long_side:
    default: 'data/02-munge/poss_long.rds'
    help: 'Path format of "long" poss data.'
  path_poss_wide_side:
    default: 'data/02-munge/poss_wide.rds'
    help: 'Path format of "wide" poss data.'


    
  path_viz_rapm_fit_cv_side:
    default: 'figs/viz_rapm_fit_cv_side.png'
    help: 'Path format of '
  path_viz_rapm_fit_side:
    default: 'figs/viz_rapm_fit_side.png'
    help: 'Path format of '
  path_lambda_side:
    default: 'data/03-fit/dump/info/lambda.csv'
    help: 'Path format of '
  path_rapm_fit_side:
    default: 'data/03-fit/rapm_fit.rds'
    help: 'Path format of RAPM model fitted for offensive/defensive poss data.'


  path_rapm_coefs_side:
    default: 'data/04-extract/dump/info/rapm_coefs.csv'
    help: 'Path format of final player-specific offensive/defensive RAPM coefs.'
  path_rapm_coefs_var_side:
    default: 'data/04-extract/dump/info/rapm_coefs_var.csv'
    help: 'Path format of RAPM model coefficent variance values.'
  path_rapm_coefs:
    default: 'data/04-extract/rapm_coefs.csv'
    help: 'Path format of final combined offensive and defensive RAPM coefs.'


    
  path_rapm_coefs_join:
    default: 'data/05-analyze/dump/info/rapm_coefs_join.csv'
    help: ''
  path_rapm_coefs_cors:
    default: 'data/05-analyze/rapm_coefs_cors.csv'
    help: ''
  path_rapm_coefs_cors_grid:
    default: 'data/05-analyze/rapm_coefs_cors_grid.csv'
    help: 'Path format of correlations of calcaulted RAPM coefficients with
    those from external data sources using a "grid" of different input parameters.
    This is useful for "tuning" the inputs to the RAPM model.'
  path_rapm_coefs_cors_grid_summary:
    default: 'data/05-analyze/rapm_coefs_cors_grid_summary.csv'
    help: '???Path format of summarized information regarding
    data imported from `path_rapm_coefs_cors_grid`.'
  path_viz_rapm_coefs_cors_grid:
    default: 'figs/viz_rapm_coefs_cors_grid.csv'
    help: 'Path format of visualization of data from `path_rapm_coefs_cors_grid`.'



  # Supplementary/meta project information (`analyze` and profiling)
  path_proj_profile:
    default: 'data/misc/proj_profile.rds'
    help: 'Path format of a profile (i.e. timing/execution order of functions)
    of the RAPM calculation for a single season.
    Not that this path will NOT have a season appended to it.'
  path_viz_proj_funcs:
    default: 'figs/viz_proj_funcs.png'
    help: 'Path format for a visual that goes "hand-in-hand"
    with `path_proj_profile`.'



  # Static data.
  path_teams_nbastatr:
    default: 'data/static/nbastatr/teams_nbastatr.csv'
    help: 'Path format of team data to export.
    Retrieved from `{nbastatR}` package.
    Important for checking the "validity" of the raw and processed data.
    Only relevant if `export = TRUE`.'
  path_players_nbastatr:
    default: 'data/static/nbastatr/players_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for player data.'
  path_teams_game_logs_nbastatr:
    default: 'data/static/nbastatr/teams_game_logs_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for team game logs data.'
  path_players_game_logs_nbastatr:
    default: 'data/static/nbastatr/players_game_logs_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for player game logs data.'
  path_teams_summary_nbastatr:
    default: 'data/static/nbastatr/teams_summary_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for team summary data.'
  path_players_summary_nbastatr:
    default: 'data/static/nbastatr/players_summary_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for player summary data.'
  path_rapm_basketballanalytics:
    default: 'data/static/basketballanalytics/rapm_basketballanalytics.csv'
    help: ''
  path_rpm_espn:
    default: 'data/static/espn/rpm_espn.csv'
    help: ''
   
production:

