default:

  # "Required" for data processing.
  path_raw_play_by_play:
    default: 'data-raw/play_by_play_with_lineup.csv'
    help: 'Path format of raw play-by-play data file to clean.'
  path_play_by_play:
    default: 'data/play_by_play.csv'
    help: 'Path format of cleaned play-by-play data file to export.'
  
  path_possession_data_o:
    default: 'data/posession_data_o.rds'
    help: 'Path format of "wide" offensive possession data to export.'
  path_possession_data_d:
    default: 'data/posession_data_d.rds'
    help: 'Analogous to `path_possession_data_o`.'
   
  path_rapm_fit_o:
    default: 'data/rapm_fit_o.rds'
    help: 'Path format of RAPM model fitted for offensive possession data.
    Only relevent if `export = `TRUE`.'
  path_rapm_fit_d:
    default: 'data/rapm_fit_d.rds'
    help: 'Analogous to `path_rapm_fit_o`.'

  path_rapm_estimates_o:
    default: 'data/rapm_estimates_o.csv'
    help: 'Path format of final the player-specific offensive RAPM estimates.
    Only relevent if `export = `TRUE`.'
  path_rapm_estimates_d:
    default: 'data/rapm_estimates_d.csv'
    help: 'Analogous to `path_rapm_estimates_o`.'
  path_rapm_estimates:
    default: 'data/rapm_estimates.csv'
    help: 'Path format of final combined offensive and defensive RAPM estimates.'

  # Used exclusively for comparisons.
  path_teams_nbastatr:
    default: 'data/teams_nbastatr.csv'
    help: 'Path format of team data to export.
    Retrieved from `{nbastatR}` package.
    Important for checking the "validity" of the raw and processed data.
    Only relevant if `export = TRUE`.'
  path_players_nbastatr:
    default: 'data/players_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for player data.'
  path_teams_game_logs_nbastatr:
    default: 'data/teams_game_logs_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for team game logs data.'
  path_players_game_logs_nbastatr:
    default: 'data/players_game_logs_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for player game logs data.'
  path_teams_summary_nbastatr:
    default: 'data/teams_summary_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for team summary data.'
  path_players_summary_nbastatr:
    default: 'data/players_summary_nbastatr.csv'
    help: 'Analogous to `path_teams_nbastatr` for player summary data.'
  
  # Used for comparisons, but also "required" by some of the other "significant", 
  # non-comparison-related data.
  path_players_summary_calc:
    default: 'data/players_summary_calc.csv'
    help: 'Path format of summarized cleaned player data.
     Relevant in the same cases as `path_possession_data_o`.
     Used to add names and other player-relevant information to final output.'
  path_teams_summary_calc:
    default: 'data/teams_summary_calc.csv'
    help: 'Analogous to `path_players_summary_calc` for team data.'
  
  # Output from comparisons.
  path_game_final_scores_compare:
    default: 'data/game_final_scores_compare.csv'
    help: ''
  path_players_game_logs_compare:
    default: 'data/players_game_logs_compare.csv'
    help: ''
  path_players_summary_compare:
    default: 'data/players_summary_compare.csv'
    help: ''
  path_teams_summary_compare:
    default: 'data/teams_summary_compare.csv'
    help: ''
    
  # Output from "debugging"-like things
  path_play_by_play_error:
    default: 'data/play_by_play_error.csv'
    help: ''
  path_stints_calc:
    default: 'data/stints_calc.csv'
    help: ''
  path_possession_data_o_error:
    default: 'data/possession_data_o_error.csv'
    help: ''
  path_possession_data_d_error:
    default: 'data/possession_data_d_error.csv'
    help: ''
   
production:

